# =====================================================================
# {{.Prog}} base config v0.2.0 (Go version, rendered by {{.Prog}})
# * The proxy-providers section is managed incrementally by sub import/sub del —
#   do not hand-edit that section (everything else is yours)
# * Port/secret changes are followed by {{.Prog}} automatically — the config
#   file is the single source of truth
#
# v0.2.0 highlights (vs the bash version v0.1.4):
#   - DNS hijacking is done by nftables (redirect -> 1053); tun.dns-hijack removed
#   - routing-mark 6666: tags mihomo's own outbound traffic so the firewall can
#     exempt it and prevent a DNS loop (do not change)
#   - tun.stack defaults to system (fine for light home loads); for heavy BT/PT,
#     long UDP streaming, frequently dropping nodes, or old kernels (5.4/5.15),
#     switching to gvisor is recommended as the unattended fallback
#   - Real resolution of foreign domains goes through the DNS group (default
#     🔃 auto-select = fastest node) via DoH
#   - NTP uses a CN source; prefer-h3 off (DNS does not die with disturbed UDP)
# =====================================================================

# ============ Anchor templates (&pr service groups / &prd CN group / &p subscription / &use generic) ============
# sub import appends the subscription name into the use lists below: one change,
# every consuming group follows
pr: &pr
  type: select
  proxies: [🔃 自动选择, 🎬 流媒体, 🎮 游戏, 🇨🇳 回国, 🇭🇰 香港, 🇹🇼 台湾, 🇯🇵 日本, 🇸🇬 新加坡, 🇰🇷 韩国, 🇺🇸 美国, 🇬🇧 英国, 🇩🇪 德国, 🇫🇷 法国, 🇳🇱 荷兰, 🇨🇦 加拿大, 🇦🇺 澳大利亚, 🇷🇺 俄罗斯, 🇹🇷 土耳其, 🇮🇳 印度, 🇲🇾 马来西亚, 🇹🇭 泰国, 🇻🇳 越南, 🇵🇭 菲律宾, 🇮🇩 印度尼西亚, 🇧🇷 巴西, 🇦🇷 阿根廷, 🌍 其他地区, 📡 全部节点, DIRECT]
  use: [SUB]
prd: &prd
  type: select
  proxies: [DIRECT, 🔃 自动选择, 🇭🇰 香港, 🇹🇼 台湾, 🇯🇵 日本, 🇸🇬 新加坡, 🇰🇷 韩国, 🇺🇸 美国, 🇬🇧 英国, 🇩🇪 德国, 🇫🇷 法国, 🇳🇱 荷兰, 🇨🇦 加拿大, 🇦🇺 澳大利亚, 🇷🇺 俄罗斯, 🇹🇷 土耳其, 🇮🇳 印度, 🇲🇾 马来西亚, 🇹🇭 泰国, 🇻🇳 越南, 🇵🇭 菲律宾, 🇮🇩 印度尼西亚, 🇧🇷 巴西, 🇦🇷 阿根廷, 🌍 其他地区, 📡 全部节点]
  use: [SUB]
# Subscription provider common template: entries generated by sub import --name reuse it via <<: *p
p: &p
  type: http
  interval: 86400
  health-check:
    enable: true
    url: https://www.gstatic.com/generate_204/
    interval: 300
    timeout: 5000
    lazy: true
    tolerance: 100
use: &use
  type: select
  use: [SUB]

# ============ Subscription sources (managed by sub import --name) ============
# Default placeholder subscription: status sees SUB_URL_PLACEHOLDER and reports
# "not set yet"; sub import rewrites SUB by default, --name <other> adds a parallel entry
proxy-providers:
  SUB:
    <<: *p
    url: "SUB_URL_PLACEHOLDER"
    path: ./proxies/SUB.yaml

# ============ Base settings ============
mixed-port: {{.MixedPort}}
port: 9966
socks-port: 6699
allow-lan: true
mode: rule
log-level: warning
ipv6: true
unified-delay: true
tcp-concurrent: true
# Gateway/router: keep off (forwarded traffic carries no process info)
find-process-mode: off
keep-alive-interval: 30
# mihomo marks its own outbound 6666, coupled with the firewall exemption to prevent a DNS loop (do not change)
routing-mark: {{.RoutingMark}}

# ============ External controller / panel ============
external-controller: 0.0.0.0:{{.ApiPort}}
external-ui: ui/official
secret: {{.Secret}}

{{- if .TProxy}}
# ============ TPROXY mode (mark/policy routing/hijack chains managed by the {{.Prog}} firewall module) ============
tproxy-port: {{.TproxyPort}}
{{- else}}
# ============ TUN transparent proxy (DNS hijack moved to the firewall, hence no dns-hijack) ============
# Parameters stay in sync with internal/asset.TunParams / TunRouteExclude (changing
# this block requires syncing the Go constants)
tun:
  enable: true
  stack: system             # home default; switch to gvisor for scenarios prone to silent TUN stalls
  auto-route: true
  auto-detect-interface: true
  strict-route: true
  mtu: 1500
  # exclude loopback/LAN to prevent proxy loops
  route-exclude-address:
    - 127.0.0.0/8
    - ::1/128
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
{{- end}}
# ============ Firewall (iptables block) ============
# Important: this iptables switch is mihomo's own "auto-write kernel rules" toggle,
# NOT panoxy's firewall backend. The DNS hijack / TPROXY mark/policy routing needed
# for transparent proxying are all managed by panoxy's own nftables rules (the
# systemd ExecStartPost runs `panoxy fw apply` to install them); mihomo only listens
# on ports. If mistakenly set to enable: true, mihomo writes another set of
# inbound-tproxy/redirect rules into the kernel — duplicating and conflicting with
# panoxy's rules, and impossible to clean up fully on uninstall. It must therefore
# stay false; do not change.
iptables:
  enable: false

# ============ Geo data ============
geodata-mode: true
geo-auto-update: true
geo-update-interval: 24
geox-url:
  geoip: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat"
  geosite: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country.mmdb"

# ============ Cache ============
profile:
  store-selected: true
  store-fake-ip: true

# ============ NTP ============
ntp:
  enable: true
  write-to-system: false
  server: ntp.aliyun.com   # on CN gateways time.apple.com (UDP 123) is often disturbed
  port: 123
  interval: 30

# ============ Domain sniffing ============
sniffer:
  enable: true
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true

# ============ DNS ============
dns:
  enable: true
  ipv6: true
  # Landing point of the firewall redirect: [::] dual-stack listen — v4 queries are
  # accepted as v4-mapped (equivalent to 0.0.0.0) while v6-transported DNS queries are
  # served too; do not change back to 127.0.0.1 (PREROUTING LAN clients must reach it).
  listen: "[::]:{{.DnsPort}}"
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-range6: 2001:2::1/48 # IPv6 fake-ip pool (RFC 5180 benchmark block); never add 2001:2::/48 to the keep6 whitelist
  prefer-h3: false          # DoH over H2/TCP
  respect-rules: true
  fake-ip-filter:
    - "*.lan"
    - "*.local"
    - "*.direct"
    - time.windows.com
    - ntp.*
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  # Real resolution of foreign domains: via the DNS group (default 🔃 auto-select =
  # fastest node) over DoH; under fake-ip the client gets a fake IP, this only fires
  # when the kernel itself needs the real IP
  nameserver:
    - https://1.1.1.1/dns-query#DNS
  # Subscription domains/node-server domains: resolvable direct from CN (the bootstrap lifeline, never proxied)
  proxy-server-nameserver:
    - https://doh.pub/dns-query
  nameserver-policy:
    "geosite:cn,private":
      - https://doh.pub/dns-query
      - 223.5.5.5
      - 119.29.29.29

# ============ Policy groups ============
proxy-groups:
  # DNS group: the outbound for the DoH servers above (the #DNS suffix); defaults to
  # 🔃 auto-select (fastest node). Deliberately no DIRECT (blocked domains would fail
  # to resolve over a direct path)
  - { name: DNS, <<: *use, proxies: [🔃 自动选择, 🇭🇰 香港, 🇹🇼 台湾, 🇯🇵 日本, 🇸🇬 新加坡, 🇰🇷 韩国, 🇺🇸 美国, 📡 全部节点] }
  - { name: 🚀 节点选择, <<: *pr }
  - { name: 🎓 学术, <<: *pr }
  - { name: 🧠 境外AI, <<: *pr }
  - { name: 🛡️ 广告拦截, type: select, proxies: [REJECT, DIRECT, 🚀 节点选择] }
  - { name: 🎵 TikTok, <<: *pr }
  - { name: 🎥 油管视频, <<: *pr }
  - { name: 🤖 ChatGPT, <<: *pr }
  - { name: 🍎 苹果服务, <<: *pr }
  - { name: Ⓜ️ 微软云盘, <<: *pr }
  - { name: Ⓜ️ 微软, <<: *pr }
  - { name: 🎮 游戏平台, <<: *pr }
  - { name: 📢 谷歌FCM, <<: *pr }
  - { name: 📲 电报服务, <<: *pr }
  - { name: 🐦 Twitter, <<: *pr }
  - { name: 💬 Copilot, <<: *pr }
  - { name: 💾 Synology, <<: *pr }
  - { name: 🧲 qBitorrent, <<: *pr }
  - { name: 🎥 网飞视频, <<: *pr }
  - { name: 🏠 国内, <<: *prd }
  - { name: 🟢 Spotify, <<: *pr }
  - { name: 🔍 GitHub, <<: *pr }
  # Fallback group: traffic no rule matched
  - { name: 🌐 其他, <<: *pr }

  # ===== Region groups (the full set: covers most airport naming; sub import prunes non-matching ones by actual nodes) =====
  - { name: 🇭🇰 香港, <<: *use, type: url-test, filter: '(?i)香港|港|HK|Hong ?Kong|HKG' }
  - { name: 🇹🇼 台湾, <<: *use, type: url-test, filter: '(?i)台湾|台北|新北|桃园|台中|台南|彰化|TW|Taiwan|TPE' }
  - { name: 🇯🇵 日本, <<: *use, type: url-test, filter: '(?i)日本|东京|東京|大阪|埼玉|冲绳|JP|Japan|Tokyo|Osaka|Narita' }
  - { name: 🇸🇬 新加坡, <<: *use, type: url-test, filter: '(?i)新加坡|狮城|SG|Singapore|SIN' }
  - { name: 🇰🇷 韩国, <<: *use, type: url-test, filter: '(?i)韩国|韩|首尔|釜山|KR|Korea|Seoul|Busan' }
  - { name: 🇺🇸 美国, <<: *use, type: url-test, filter: '(?i)美国|美西|美东|美中|洛杉矶|圣何塞|西雅图|纽约|波特兰|硅谷|US|United ?States|America|Los ?Angeles|San ?Jose|Seattle|New ?York' }
  - { name: 🇬🇧 英国, <<: *use, type: url-test, filter: '(?i)英国|英|伦敦|UK|United ?Kingdom|Britain|London' }
  - { name: 🇩🇪 德国, <<: *use, type: url-test, filter: '(?i)德国|德|法兰克福|DE|Germany|Frankfurt' }
  - { name: 🇫🇷 法国, <<: *use, type: url-test, filter: '(?i)法国|法|巴黎|FR|France|Paris' }
  - { name: 🇳🇱 荷兰, <<: *use, type: url-test, filter: '(?i)荷兰|荷|阿姆斯特丹|NL|Netherlands|Amsterdam' }
  - { name: 🇨🇦 加拿大, <<: *use, type: url-test, filter: '(?i)加拿大|加|多伦多|温哥华|CA|Canada|Toronto|Vancouver' }
  - { name: 🇦🇺 澳大利亚, <<: *use, type: url-test, filter: '(?i)澳大利亚|澳洲|悉尼|墨尔本|AU|Australia|Sydney|Melbourne' }
  - { name: 🇷🇺 俄罗斯, <<: *use, type: url-test, filter: '(?i)俄罗斯|俄|莫斯科|RU|Russia|Moscow' }
  - { name: 🇹🇷 土耳其, <<: *use, type: url-test, filter: '(?i)土耳其|土|伊斯坦布尔|TR|Turkey|Istanbul' }
  - { name: 🇮🇳 印度, <<: *use, type: url-test, filter: '(?i)印度|印|孟买|IN|India|Mumbai' }
  - { name: 🇲🇾 马来西亚, <<: *use, type: url-test, filter: '(?i)马来西亚|马来|吉隆坡|MY|Malaysia|Kuala ?Lumpur' }
  - { name: 🇹🇭 泰国, <<: *use, type: url-test, filter: '(?i)泰国|泰|曼谷|TH|Thailand|Bangkok' }
  - { name: 🇻🇳 越南, <<: *use, type: url-test, filter: '(?i)越南|越|胡志明|河内|VN|Vietnam|Ho ?Chi ?Minh|Hanoi' }
  - { name: 🇵🇭 菲律宾, <<: *use, type: url-test, filter: '(?i)菲律宾|菲|马尼拉|PH|Philippines|Manila' }
  - { name: 🇮🇩 印度尼西亚, <<: *use, type: url-test, filter: '(?i)印度尼西亚|印尼|雅加达|ID|Indonesia|Jakarta' }
  - { name: 🇧🇷 巴西, <<: *use, type: url-test, filter: '(?i)巴西|巴|圣保罗|BR|Brazil|Sao ?Paulo' }
  - { name: 🇦🇷 阿根廷, <<: *use, type: url-test, filter: '(?i)阿根廷|阿|布宜诺斯|AR|Argentina|Buenos ?Aires' }
  - { name: 🌍 其他地区, <<: *use, type: url-test, filter: '(?i)阿联酋|迪拜|沙特|南非|墨西哥|智利|波兰|瑞典|瑞士|挪威|丹麦|芬兰|奥地利|比利时|西班牙|意大利|葡萄牙|爱尔兰|捷克|乌克兰|UAE|Dubai|Saudi|South ?Africa|Mexico|Chile|Poland|Sweden|Switzerland|Norway|Denmark|Finland|Austria|Belgium|Spain|Italy|Portugal|Ireland|Czech|Ukraine' }

  # ===== Type groups (derived from node purpose; sub import prunes non-matching ones by actual nodes) =====
  - { name: 🎬 流媒体, <<: *use, type: url-test, filter: '(?i)流媒体|解锁|原生IP|原生|奈飞|网飞|Netflix|Disney|迪士尼|媒体|Media|影视|4K|Streaming' }
  - { name: 🎮 游戏, <<: *use, type: url-test, filter: '(?i)游戏|电竞|低延迟|Game|Gaming|IEPL|IPLC|专线|内网' }
  - { name: 🇨🇳 回国, <<: *use, type: url-test, filter: '(?i)回国|大陆|中国|China|CN2|回国线路|国内中转' }

  # Fallback groups (no filter, never pruned)
  - { name: 📡 全部节点, <<: *use }
  - { name: 🔃 自动选择, <<: *use, tolerance: 2, type: url-test }

# ============ Rule providers ============
rule-providers:
  # HyperADRules aggregated ad/malicious-domain blocking https://github.com/Lynricsy/HyperADRules
  # Published on GitHub Releases (unreachable direct from CN): the offline package
  # pre-seeds the cache file with the same name, so the first start works offline;
  # later, when the kernel refreshes subscriptions/rules, traffic goes through nodes
  # by its own rules and updates resume automatically
  HyperADRules-Ads:
    type: http
    behavior: domain
    format: yaml
    path: ./rule_provider/HyperADRules-Ads.yaml
    url: "https://github.com/Lynricsy/HyperADRules/releases/latest/download/hyper_adrules_ads_clash.yaml"
    interval: 86400

# ============ Routing rules ============
# Principle: no protocol is blocked (QUIC/DoT/DoQ/DoH all get normal routing); the
# first goal of transparent proxying is normal access.
# DNS port 53 is hijacked as usual (domain-level routing for most devices); encrypted
# DNS (853/443) goes through the proxy (preserved for custom devices).
rules:
  # ===== Basic direct services (never proxied; keeps SSH/VPN/remote desktop/VoIP/IoT working) =====
  #- DST-PORT,22,DIRECT                             # SSH/SFTP (disabled: foreign SSH goes through the proxy; GitHub SSH avoids pollution)
  - DST-PORT,23,DIRECT                              # Telnet
  - DST-PORT,3389,DIRECT                            # RDP remote desktop (latency-sensitive)
  - DST-PORT,5900,DIRECT                            # VNC remote desktop
  - DST-PORT,5060,DIRECT                            # SIP (VoIP signaling)
  - DST-PORT,5061,DIRECT                            # SIPS (SIP over TLS)
  - DST-PORT,1900,DIRECT                            # SSDP/UPnP device discovery
  - DST-PORT,88,DIRECT                              # Kerberos domain auth
  - DST-PORT,389,DIRECT                             # LDAP
  - DST-PORT,636,DIRECT                             # LDAPS
  - DST-PORT,1812,DIRECT                            # RADIUS auth
  - DST-PORT,1813,DIRECT                            # RADIUS accounting
  - DST-PORT,41641,DIRECT                           # Tailscale direct UDP
  - DST-PORT,3478,DIRECT                            # STUN/TURN (NAT traversal)
  - DST-PORT,51820,DIRECT                           # WireGuard
  - DST-PORT,1194,DIRECT                            # OpenVPN
  - DST-PORT,500,DIRECT                             # IPSec IKE (UDP 500)
  - DST-PORT,4500,DIRECT                            # IPSec NAT-T (UDP 4500)
  - DST-PORT,1701,DIRECT                            # L2TP (UDP 1701)
  - DST-PORT,1723,DIRECT                            # PPTP (TCP 1723)
  - DST-PORT,5353,DIRECT                            # mDNS (LAN discovery)
  - DST-PORT,123,DIRECT                             # NTP (time sync)
  - DST-PORT,161,DIRECT                             # SNMP (network management)
  - DST-PORT,1883,DIRECT                            # MQTT(IoT)
  - DST-PORT,8883,DIRECT                            # MQTT over TLS
  - DST-PORT,5683,DIRECT                            # CoAP(IoT)
  - DST-PORT,3260,DIRECT                            # iSCSI (IP storage)
  - DST-PORT,3306,DIRECT                            # MySQL
  - DST-PORT,5432,DIRECT                            # PostgreSQL
  - DST-PORT,6379,DIRECT                            # Redis
  - DST-PORT,27017,DIRECT                           # MongoDB
  - DST-PORT,873,DIRECT                             # Rsync
  - IP-CIDR,100.100.100.100/32,DIRECT,no-resolve    # Tailscale MagicDNS
  - IP-CIDR,100.64.0.0/10,DIRECT,no-resolve         # Tailscale subnet (CGNAT)

  # ===== App routing =====
  - GEOSITE,TikTok,🎵 TikTok
  - DOMAIN-SUFFIX,chatgpt.com,🤖 ChatGPT
  - DOMAIN-SUFFIX,oaistatic.com,🤖 ChatGPT
  - DOMAIN-SUFFIX,oaiusercontent.com,🤖 ChatGPT
  - DOMAIN-SUFFIX,openai.com,🤖 ChatGPT
  - DOMAIN-SUFFIX,openai.com.cdn.cloudflare.net,🤖 ChatGPT
  - DOMAIN-SUFFIX,openaiapi-site.azureedge.net,🤖 ChatGPT
  - DOMAIN-SUFFIX,openaicom-api-bdcpf8c6d2e9atf6.z01.azurefd.net,🤖 ChatGPT
  - DOMAIN-SUFFIX,openaicomproductionae4b.blob.core.windows.net,🤖 ChatGPT
  - DOMAIN-SUFFIX,production-openaicom-storage.azureedge.net,🤖 ChatGPT
  - RULE-SET,HyperADRules-Ads,🛡️ 广告拦截
  - GEOSITE,category-scholar-!cn,🎓 学术
  - GEOSITE,category-ai-!cn,🧠 境外AI
  - GEOSITE,steam@cn,DIRECT
  - GEOSITE,steam,🎮 游戏平台
  - GEOSITE,apple,🍎 苹果服务
  - GEOSITE,onedrive,Ⓜ️ 微软云盘
  - GEOSITE,apple-cn,🍎 苹果服务
  - GEOSITE,github,🔍 GitHub
  - GEOSITE,twitter,🐦 Twitter
  - DOMAIN-KEYWORD,synology,💾 Synology
  - DOMAIN-KEYWORD,copilot,💬 Copilot
  - GEOSITE,bing,Ⓜ️ 微软
  - GEOSITE,microsoft,Ⓜ️ 微软
  - GEOSITE,msn,Ⓜ️ 微软
  - GEOSITE,youtube,🎥 油管视频
  - GEOSITE,google,📢 谷歌FCM
  - GEOSITE,google-cn,📢 谷歌FCM
  - GEOSITE,telegram,📲 电报服务
  - GEOSITE,netflix,🎥 网飞视频
  - GEOSITE,spotify,🟢 Spotify
  - GEOSITE,geolocation-!cn,🌐 其他
  - GEOIP,google,📢 谷歌FCM
  - GEOIP,netflix,🎥 网飞视频
  - GEOIP,telegram,📲 电报服务
  - GEOIP,twitter,🐦 Twitter
  - GEOSITE,CN,🏠 国内
  - GEOIP,CN,🏠 国内
  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  - IP-CIDR,100.64.0.0/10,DIRECT,no-resolve
  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
  - MATCH,🌐 其他
